### ISSUE TITLE
Days are off by 1, Saturday shows as the first day of the week

### ISSUE THREAD

**Issue by omanizer** [youngerheart/vue-daterangepicker#9]
The top of the calendar looks like this (on both range and date type calendars);

Sat  Sun  Mon  Tue  Wed  Thu  Fri

The actual structure of the calendar is correct (the days are all in the correct columns) but since these days are off it makes it appear that March 23, 2016 is a Tuesday when it is a Wednesday.

It appears to be coming from this line:
`for(var n=[],r=0;7>r;r++)n.push(moment().weekday(r-1).format("ddd"));`

When I change "r-1" to "r" it fixes the issue.  I'm unsure whether this will affect anything else or why this subtraction was added in the first place.  It's all minified code so I hate to muck around with it.

**Comment by youngerheart** [comment]
yes, it's a interesting bug, because Chinese weekday start on Monday and western start on Sunday.

```
moment.weekday(0).format('MM-DD') // 04-03
moment.locale('zh-cn')
moment.weekday(0).format('MM-DD') // 04-04
```

Days are all in the correct columns is I needed. but I only considering Chinese situation before.

I'll fix that like

```
weekdays.push(moment().weekday(this.lang.indexOf('cn') === -1 ? i : i - 1).format('ddd'));
```

thanks for your issue!
